import { Analytics } from "@vercel/analytics/react"
import { IBM_Plex_Sans, Rubik, Schibsted_Grotesk } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const display = IBM_Plex_Sans({ subsets: ["latin"], weight: ["400", "600", "700" ] });

export const metadata: Metadata = {
  title: "Dynamic Island",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased">
      <body className={display.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
